### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by IWareQ** [PetteriM1/ItemLifeTime#1]
Please update plugins

**Comment by PetteriM1** [comment]
> Please update plugins

Update what?

**Comment by IWareQ** [comment]
The plugin does not work on 1.16, can you please update it?

**Comment by PetteriM1** [comment]
> > Please update plugins
> 
> Update what?

What is the problem with it?

**Comment by IWareQ** [comment]
> > > Please update plugins
> > 
> > Update what?
> 
> What is the problem with it?

The plugin does not work on 1.16

**Comment by PetteriM1** [comment]
> > > > Please update plugins
> > > 
> > > Update what?
> > 
> > What is the problem with it?
> 
> The plugin does not work on 1.16

"Not working" is the worst possible description you can give in a bug report. If you want something to be fixed then you at least gotta tell what is not working

**Comment by IWareQ** [comment]
> > > > > Please update plugins
> > > > 
> > > > Update what?
> > > 
> > > What is the problem with it?
> > 
> > The plugin does not work on 1.16
> 
> "Not working" is the worst possible description you can give in a bug report. If you want something to be fixed then you at least gotta tell what is not working

The plugin crashes, the counter above the items does not appear, the items do not disappear

**Comment by PetteriM1** [comment]
> > > > > > Please update plugins
> > > > > 
> > > > > Update what?
> > > > 
> > > > What is the problem with it?
> > > 
> > > The plugin does not work on 1.16
> > 
> > "Not working" is the worst possible description you can give in a bug report. If you want something to be fixed then you at least gotta tell what is not working
> 
> The plugin crashes, the counter above the items does not appear, the items do not disappear

If it crashes could you send the stack trace?
